def customer_type_features(ct):
    if ct=='New':
        cont_features=['ABANDONED','AGE_SPOUSE','STATE_ATTACH_COUNT',	'AGE_TAXPAYER',	'AMOUNT_STUDENT_LOAN_INTEREST_DEDUCTION',	'AMOUNT_UNEMPLOYMENT',		'FLAG_ITEMIZED_DEDUCTIONS',		'NUM_DEPENDENTS',	'NUM_EXEMPTIONS',	'NUM_SCHC',	'NUM_SCHE',	'NUM_W2',	'REJECT_COUNT',	'SESSIONS_TO_COMPLETE',	'TOTAL_REVENUE']

        bool_features=['ABANDONED',	'FLAG_ITEMIZED_DEDUCTIONS']
        catag_features=['FILING_STATUS','LAST_STATUS','CUSTOMER_TYPE','PRS_SCORE','COMPLETED_SKU','DMA_AREA',	'FED_FORM_TYPE','FIRST_COMPLETE_APP_TYPE','FIRST_COMPLETE_DEVICE_TYPE','IMPORT_TYPE','NEAUTH_DEVICE_TYPE','PRODUCT_EDITION_DESCRIPTION','START_SKU','VAUTH_DEVICE_TYPE']

        cont_score_features = [ 'AGE_SPOUSE', 'AGE_TAXPAYER', 'AMOUNT_STUDENT_LOAN_INTEREST_DEDUCTION',
                         'AMOUNT_UNEMPLOYMENT',  'FLAG_ITEMIZED_DEDUCTIONS',
                          'NUM_DEPENDENTS', 'NUM_EXEMPTIONS', 'NUM_SCHC', 'NUM_SCHE', 'NUM_W2','STATE_ATTACH_COUNT',
                         'REJECT_COUNT', 'SESSIONS_TO_COMPLETE', 'TOTAL_REVENUE']

        bool_score_features = ['FLAG_ITEMIZED_DEDUCTIONS']
        catag_score_features = ['FILING_STATUS',	'LAST_STATUS',	'CUSTOMER_TYPE',	'PRS_SCORE',	'COMPLETED_SKU',	'DMA_AREA',	'FED_FORM_TYPE',	'FIRST_COMPLETE_APP_TYPE',	'FIRST_COMPLETE_DEVICE_TYPE',	'IMPORT_TYPE',	'NEAUTH_DEVICE_TYPE',	'PRODUCT_EDITION_DESCRIPTION',	'START_SKU',		'VAUTH_DEVICE_TYPE']


    return cont_features, bool_features, catag_features, cont_score_features, bool_score_features, catag_score_features