def tto_pricing_features(ct):
    if ct=='New':
        cont_features=['AGE_DEPENDENT_AVG_CY',	'AGE_SPOUSE_CY',	'AGE_TAXPAYER_CY',	'AMOUNT_CHILD_CARE_CREDIT',	'AMOUNT_EITC',	'AMOUNT_HOPE_CREDIT_CY',	'AMOUNT_STUDENT_LOAN_INTEREST_DEDUCTION_CY',	'auth_id_age_role_CY',	'FLAG_OLD_OR_BLIND_CY',	'MAX_REVENUE',	'MINDBENDER_REVENUE',	'NON_CA_REFUND_TRANSFER_REVENUE',	'NUM_EXEMPTIONS_CY',	'ORDER_AMOUNT',	'PS_REVENUE',	'SESSIONS_TO_COMPLETE',	'STATE_ATTACH_COUNT',	'STATE_REVENUE',	'AGE_SPOUSE',	'AGE_TAXPAYER',	'AMOUNT_CHILD_CREDIT_CY',	'AMOUNT_STUDENT_LOAN_INTEREST_DEDUCTION',	'COST_PER_CHANNEL_DAY',	'NUM_DEPENDENTS_CY',	'NUM_EXEMPTIONS',	'NUM_W2',	'AGE_DEPENDENT_MAX',	'AMOUNT_CHILD_CARE_CREDIT_CY',	'AMOUNT_CHILD_CREDIT',	'AMOUNT_EITC_CY',	'AMOUNT_SOCIAL_SEC',	'AMOUNT_TOTAL_INCOME',	'BUS_ACCOUNTING_METHOD_CASH',	'NUM_DEPENDENTS','TOTAL_REVENUE_CY']

        bool_features=[	'FLAG_OLD_OR_BLIND_CY']

        catag_features=['PRS_SCORE_CY',	'TAX_DAY',	'start_sku_rollup_id_CY']

        cont_score_features = ['AGE_DEPENDENT_AVG_CY', 'AGE_SPOUSE_CY', 'AGE_TAXPAYER_CY', 'AMOUNT_CHILD_CARE_CREDIT',
                         'AMOUNT_EITC', 'AMOUNT_HOPE_CREDIT_CY', 'AMOUNT_STUDENT_LOAN_INTEREST_DEDUCTION_CY',
                         'auth_id_age_role_CY', 'FLAG_OLD_OR_BLIND_CY', 'MAX_REVENUE', 'MINDBENDER_REVENUE',
                         'NON_CA_REFUND_TRANSFER_REVENUE', 'NUM_EXEMPTIONS_CY', 'ORDER_AMOUNT', 'PS_REVENUE',
                         'SESSIONS_TO_COMPLETE', 'STATE_ATTACH_COUNT', 'STATE_REVENUE', 'AGE_SPOUSE', 'AGE_TAXPAYER',
                         'AMOUNT_CHILD_CREDIT_CY', 'AMOUNT_STUDENT_LOAN_INTEREST_DEDUCTION', 'COST_PER_CHANNEL_DAY',
                         'NUM_DEPENDENTS_CY', 'NUM_EXEMPTIONS', 'NUM_W2', 'AGE_DEPENDENT_MAX',
                         'AMOUNT_CHILD_CARE_CREDIT_CY', 'AMOUNT_CHILD_CREDIT', 'AMOUNT_EITC_CY', 'AMOUNT_SOCIAL_SEC',
                         'AMOUNT_TOTAL_INCOME', 'BUS_ACCOUNTING_METHOD_CASH', 'NUM_DEPENDENTS']

        bool_score_features = ['FLAG_OLD_OR_BLIND_CY']

        catag_score_features = ['PRS_SCORE_CY', 'TAX_DAY', 'start_sku_rollup_id_CY']

    return cont_features, bool_features, catag_features, cont_score_features, bool_score_features, catag_score_features