def tto_pricing_features(ct):
    if ct=='New':
        cont_features=['AGE_DEPENDENT_MAX',	'AGE_SPOUSE',	'AGE_TAXPAYER',	'AMOUNT_CHILD_CARE_CREDIT',	'AMOUNT_EDUCATION_CREDIT',	'AMOUNT_EITC',	'AMOUNT_HOPE_CREDIT',	'AMOUNT_STUDENT_LOAN_INTEREST_DEDUCTION',	'FSCHA_FLAG',	'FSCHD_FLAG',	'FSCHE_FLAG',	'MAX_FLAG',	'MISC1099_FLAG',	'NON_CA_REFUND_TRANSFER_FLAG',	'NUM_CARE_CONTACTS',	'POST_TOTAL_VOTES',	'PRE_TOTAL_VOTES',	'REJECT_COUNT',	'REQUIRED_TAKE_FLAG',	'student_taxpayer',	'REFUND_TRANSFER_FLAG',	'SESSIONS_TO_COMPLETE','TOTAL_REVENUE_CY']

        bool_features=[	'FSCHA_FLAG',	'FSCHD_FLAG',	'FSCHE_FLAG',	'MAX_FLAG',	'MISC1099_FLAG',	'NON_CA_REFUND_TRANSFER_FLAG',	'REQUIRED_TAKE_FLAG',	'student_taxpayer',	'REFUND_TRANSFER_FLAG']

        catag_features=['CHANNEL',	'CUSTOMER_DEFINITION_ADJ',	'DMA_AREA',	'ENTRY_PAGE_GROUP',	'FED_FORM_TYPE',	'FILING_STATUS',	'FIRST_COMPLETE_APP_TYPE',	'IMPORT_TYPE',	'LAST_STATUS',	'NEAUTH_DEVICE_TYPE',	'NUM_SCHC',	'PRODUCT_EDITION_DESCRIPTION',	'PRS_SCORE',	'START_DEVICE_TYPE',	'STATE_ATTACH_COUNT',	'VAUTH_DEVICE_TYPE']

        cont_score_features = ['AGE_DEPENDENT_MAX', 'AGE_SPOUSE', 'AGE_TAXPAYER', 'AMOUNT_CHILD_CARE_CREDIT',
                         'AMOUNT_EDUCATION_CREDIT', 'AMOUNT_EITC', 'AMOUNT_HOPE_CREDIT',
                         'AMOUNT_STUDENT_LOAN_INTEREST_DEDUCTION', 'FSCHA_FLAG', 'FSCHD_FLAG', 'FSCHE_FLAG', 'MAX_FLAG',
                         'MISC1099_FLAG', 'NON_CA_REFUND_TRANSFER_FLAG', 'NUM_CARE_CONTACTS', 'POST_TOTAL_VOTES',
                         'PRE_TOTAL_VOTES', 'REJECT_COUNT', 'REQUIRED_TAKE_FLAG', 'student_taxpayer',
                         'REFUND_TRANSFER_FLAG', 'SESSIONS_TO_COMPLETE']

        bool_score_features = ['FSCHA_FLAG', 'FSCHD_FLAG', 'FSCHE_FLAG', 'MAX_FLAG', 'MISC1099_FLAG',
                         'NON_CA_REFUND_TRANSFER_FLAG', 'REQUIRED_TAKE_FLAG', 'student_taxpayer',
                         'REFUND_TRANSFER_FLAG']

        catag_score_features = ['CHANNEL', 'CUSTOMER_DEFINITION_ADJ', 'DMA_AREA', 'ENTRY_PAGE_GROUP', 'FED_FORM_TYPE',
                          'FILING_STATUS', 'FIRST_COMPLETE_APP_TYPE', 'IMPORT_TYPE', 'LAST_STATUS',
                          'NEAUTH_DEVICE_TYPE', 'NUM_SCHC', 'PRODUCT_EDITION_DESCRIPTION', 'PRS_SCORE',
                          'START_DEVICE_TYPE', 'STATE_ATTACH_COUNT', 'VAUTH_DEVICE_TYPE']

    return cont_features, bool_features, catag_features, cont_score_features, bool_score_features, catag_score_features