def tto_pricing_features(ct):
    if ct=='New':

        cont_features=['TOTAL_REVENUE_CY','AUDIT_DEFENSE_FLAG_PY',	'CA_AUDIT_DEFENSE_FLAG_PY',	'CA_MAX_FLAG_PY',	'CA_REFUND_TRANSFER_FLAG_PY',	'CORE_FLAG_PY',	'FLAG_ITEMIZE_SEPARATELY_PY',	'FLAG_ITEMIZED_DEDUCTIONS_PY',	'FLAG_OLD_OR_BLIND_PY',	'FSCHA_FLAG_PY',	'FSCHC_FLAG_PY',	'FSCHCEZ_FLAG_PY',	'FSCHD_FLAG_PY',	'FSCHE_FLAG_PY',	'FSCHF_FLAG_PY',	'MAX_FLAG_PY',	'MINDBENDER_FLAG_PY',	'MISC1099_FLAG_PY',	'NON_CA_AUDIT_DEFENSE_FLAG_PY',	'NON_CA_MAX_FLAG_PY',	'NON_CA_REFUND_TRANSFER_FLAG_PY',	'PS_FLAG_PY',	'REFUND_TRANSFER_FLAG_PY',	'REQUIRED_TAKE_FLAG_PY',	'risk_flag_PY',	'RT_FLAG_PY',	'TTO_FLAG_PY',	'tto_start_flag_PY',	'vauth_flag_PY',	'_taxpayer_PY',	'accountant_spouse_PY',	'accountant_taxpayer_PY',	'accounting_spouse_PY',	'accountmanager_spouse_PY',	'accountmanager_taxpayer_PY',	'administrativeassistant_spouse_PY',	'administrativeassistant_taxpayer_PY',	'administrator_spouse_PY',	'analyst_spouse_PY',	'analyst_taxpayer_PY',	'assistantmanager_spouse_PY',	'assistantmanager_taxpayer_PY',	'attorney_spouse_PY',	'attorney_taxpayer_PY',	'banker_spouse_PY',	'banker_taxpayer_PY',	'bankteller_spouse_PY',	'bankteller_taxpayer_PY',	'barista_taxpayer_PY',	'bartender_spouse_PY',	'bartender_taxpayer_PY',	'bookkeeper_spouse_PY',	'caregiver_spouse_PY',	'caregiver_taxpayer_PY',	'carpenter_spouse_PY',	'carpenter_taxpayer_PY',	'cashier_spouse_PY',	'cashier_taxpayer_PY',	'chef_spouse_PY',	'chef_taxpayer_PY',	'clerical_spouse_PY',	'clerk_spouse_PY',	'clerk_taxpayer_PY',	'cna_spouse_PY',	'cna_taxpayer_PY',	'construction_spouse_PY',	'construction_taxpayer_PY',	'consultant_spouse_PY',	'consultant_taxpayer_PY',	'cook_spouse_PY',	'cook_taxpayer_PY',	'correctionalofficer_taxpayer_PY',	'crewmember_taxpayer_PY',	'csr_taxpayer_PY',	'custodian_spouse_PY',	'custodian_taxpayer_PY',	'customerservice_spouse_PY',	'customerservice_taxpayer_PY',	'customerservicerep_spouse_PY',	'customerservicerep_taxpayer_PY',	'deliverydriver_taxpayer_PY',	'dentalassistant_spouse_PY',	'dentalassistant_taxpayer_PY',	'director_spouse_PY',	'disable_spouse_PY',	'disabled_spouse_PY',	'disabled_taxpayer_PY',	'dispatcher_taxpayer_PY',	'driver_spouse_PY',	'driver_taxpayer_PY',	'educator_spouse_PY',	'electrician_spouse_PY',	'electrician_taxpayer_PY',	'employed_taxpayer_PY',	'employee_taxpayer_PY',	'engineer_spouse_PY',	'engineer_taxpayer_PY',	'executiveassistant_spouse_PY',	'factory_taxpayer_PY',	'factoryworker_spouse_PY',	'factoryworker_taxpayer_PY',	'fastfood_taxpayer_PY',	'foodservice_spouse_PY',	'foodservice_taxpayer_PY',	'generallabor_taxpayer_PY',	'generalmanager_taxpayer_PY',	'graphicdesigner_spouse_PY',	'hairstylist_spouse_PY',	'home_maker_spouse_PY',	'home_spouse_PY',	'homemaker_spouse_PY',	'homemaker_taxpayer_PY',	'hostess_taxpayer_PY',	'house_wife_spouse_PY',	'housekeeper_spouse_PY',	'housekeeper_taxpayer_PY',	'housekeeping_taxpayer_PY',	'housewife_spouse_PY',	'humanresources_spouse_PY',	'janitor_taxpayer_PY',	'labor_spouse_PY',	'labor_taxpayer_PY',	'laborer_spouse_PY',	'laborer_taxpayer_PY',	'lpn_spouse_PY',	'lpn_taxpayer_PY',	'machineoperator_spouse_PY',	'machineoperator_taxpayer_PY',	'machinist_spouse_PY',	'machinist_taxpayer_PY',	'maintenance_spouse_PY',	'maintenance_taxpayer_PY',	'management_taxpayer_PY',	'manager_spouse_PY',	'manager_taxpayer_PY',	'manufacturing_taxpayer_PY',	'marketing_spouse_PY',	'marketing_taxpayer_PY',	'mechanic_spouse_PY',	'mechanic_taxpayer_PY',	'medicalassistant_spouse_PY',	'medicalassistant_taxpayer_PY',	'military_spouse_PY',	'military_taxpayer_PY',	'mom_spouse_PY',	'mother_spouse_PY',	'na_spouse_PY',	'na_spouse2_PY',	'na_taxpayer_PY',	'none_spouse_PY',	'none_taxpayer_PY',	'nurse_spouse_PY',	'nurse_taxpayer_PY',	'officeassistant_spouse_PY',	'officemanager_spouse_PY',	'officemanager_taxpayer_PY',	'operationsmanager_taxpayer_PY',	'operator_taxpayer_PY',	'painter_taxpayer_PY',	'paralegal_spouse_PY',	'pharmacist_spouse_PY',	'pharmacytechnician_spouse_PY',	'pharmacytechnician_taxpayer_PY',	'physicaltherapist_spouse_PY',	'physician_spouse_PY',	'plumber_taxpayer_PY',	'policeofficer_spouse_PY',	'policeofficer_taxpayer_PY',	'production_taxpayer_PY',	'professor_spouse_PY',	'projectmanager_spouse_PY',	'projectmanager_taxpayer_PY',	'receptionist_spouse_PY',	'receptionist_taxpayer_PY',	'registerednurse_spouse_PY',	'registerednurse_taxpayer_PY',	'retail_spouse_PY',	'retail_taxpayer_PY',	'retailmanager_spouse_PY',	'retailmanager_taxpayer_PY',	'retired_spouse_PY',	'retired_taxpayer_PY',	'rn_spouse_PY',	'rn_taxpayer_PY',	'sales_spouse_PY',	'sales_taxpayer_PY',	'salesassociate_spouse_PY',	'salesassociate_taxpayer_PY',	'salesmanager_spouse_PY',	'salesmanager_taxpayer_PY',	'secretary_spouse_PY',	'secretary_taxpayer_PY',	'security_taxpayer_PY',	'securityguard_taxpayer_PY',	'securityofficer_taxpayer_PY',	'self_employed_spouse_PY',	'selfemployed_spouse_PY',	'selfemployed_taxpayer_PY',	'server_spouse_PY',	'server_taxpayer_PY',	'socialworker_spouse_PY',	'socialworker_taxpayer_PY',	'softwareengineer_spouse_PY',	'softwareengineer_taxpayer_PY',	'stayathomemom_spouse_PY',	'stayathomemother_spouse_PY',	'stayathomeparent_spouse_PY',	'stocker_taxpayer_PY',	'storemanager_taxpayer_PY',	'student_spouse_PY',	'student_taxpayer_PY',	'substituteteacher_spouse_PY',	'supervisor_spouse_PY',	'supervisor_taxpayer_PY',	'teacher_spouse_PY',	'teacher_taxpayer_PY',	'technician_spouse_PY',	'technician_taxpayer_PY',	'truckdriver_spouse_PY',	'truckdriver_taxpayer_PY',	'unemployed_spouse_PY',	'unemployed_taxpayer_PY',	'unemployeed_spouse_PY',	'waitress_spouse_PY',	'waitress_taxpayer_PY',	'warehouse_spouse_PY',	'warehouse_taxpayer_PY',	'warehouseworker_taxpayer_PY',	'welder_spouse_PY',	'welder_taxpayer_PY',	'worker_taxpayer_PY',	'NUM_CARE_CONTACTS_PY',	'NUM_SCHC_PY',	'NUM_SCHE_PY',	'NUM_W2_PY',	'REJECT_COUNT_PY',	'STATE_ATTACH_COUNT_PY',	'FEDERAL_REVENUE_PY',	'TOTAL_REVENUE_PY',	'AGI_PY',	'AMOUNT_ADJUSTMENTS_PY',	'AMOUNT_ALIMONY_INCOME_PY',	'AMOUNT_ALIMONY_PAID_PY',	'AMOUNT_AMT_PY',	'AMOUNT_BUSINESS_INCOME_PY',	'AMOUNT_CAPITAL_GAIN_PY',	'AMOUNT_CASUALTY_LOSSES_PY',	'AMOUNT_CERTAIN_BUSINESS_EXPENSE_PY',	'AMOUNT_CHARITABLE_CONTRIBUTIONS_CARRYOVER_PY',	'AMOUNT_CHARITABLE_CONTRIBUTIONS_CASH_PY',	'AMOUNT_CHARITABLE_CONTRIBUTIONS_NONCASH_PY',	'AMOUNT_CHARITABLE_CONTRIBUTIONS_PY',	'AMOUNT_CHILD_CARE_CREDIT_PY',	'AMOUNT_CHILD_CREDIT_PY',	'AMOUNT_DEDUCTIBLE_SELF_EMPLOYMENT_TAX_PY',	'AMOUNT_DISABLED_CREDIT_PY',	'AMOUNT_DOMESTIC_PRODUCTION_DEDUCTION_PY',	'AMOUNT_EARLY_WITHDRAWAL_PENALTY_PY',	'AMOUNT_EDUCATION_CREDIT_PY',	'AMOUNT_EITC_PY',	'AMOUNT_EMPLOYEE_EXPENSES_PY',	'AMOUNT_ESTIMATED_TAX_PENALTY_PY',	'AMOUNT_ESTIMATED_TAX_PY',	'AMOUNT_EXCESS_SS_RRTA_WITHHELD_PY',	'AMOUNT_EXEMPTIONS_PY',	'AMOUNT_EXPENSES_DEDUCTION_PY',	'AMOUNT_FARM_INCOME_PY',	'AMOUNT_FOREIGN_TAX_CREDIT_PY',	'AMOUNT_FUEL_TAX_CREDIT_PY',	'AMOUNT_HOMEBUYER_CREDIT_REPAYMENT_PY',	'AMOUNT_HOPE_CREDIT_PY',	'AMOUNT_HSA_PY',	'AMOUNT_INCOME_TAX_PY',	'AMOUNT_INCOME_TAX_WITHHELD_PY',	'AMOUNT_INVESTMENT_INTEREST_PAID_PY',	'AMOUNT_IRA_DEDUCTION_PY',	'AMOUNT_IRA_DISTRIBUTIONS_PY',	'AMOUNT_MEDICAL_DENTAL_EXPENSES_DEDUCTION_PY',	'AMOUNT_MEDICAL_DENTAL_EXPENSES_PY',	'AMOUNT_MISC_DEDUCTIONS_PY',	'AMOUNT_MORTGAGE_INSURANCE_PY',	'AMOUNT_MORTGAGE_INTEREST_NON_1098_PY',	'AMOUNT_MORTGAGE_INTEREST_PY',	'AMOUNT_MORTGAGE_POINTS_NON_1098_PY',	'AMOUNT_MOVING_EXPENSE_PY',	'AMOUNT_NT_COMBAT_PAY_PY',	'AMOUNT_ORDINARY_DIVIDENDS_PY',	'AMOUNT_OTHER_CREDITS_PY',	'AMOUNT_OTHER_DEDUCTIBLE_EXPENSES_PY',	'AMOUNT_OTHER_DEDUCTIBLE_TAXES_PY',	'AMOUNT_OTHER_GAIN_PY',	'AMOUNT_OTHER_INCOME_PY',	'AMOUNT_OTHER_PAYMENTS_PY',	'AMOUNT_OTHER_TAXES_PY',	'AMOUNT_PAID_WITH_EXTENSION_PY',	'AMOUNT_PERSONAL_PROPERTY_TAXES_PY',	'AMOUNT_QUALIFIED_DIVIDENDS_PY',	'AMOUNT_REAL_ESTATE_TAX_PY',	'AMOUNT_REFUND_PY',	'AMOUNT_RESIDENTIAL_ENERGY_CREDIT_PY',	'AMOUNT_RETIREMENT_SAVINGS_CREDIT_PY',	'AMOUNT_SALARIES_AND_WAGES_PY',	'AMOUNT_SCHE_PY',	'AMOUNT_SELF_EMPLOYMENT_HEALTH_INSURANCE_PY',	'AMOUNT_SELF_EMPLOYMENT_RETIREMENT_PY',	'AMOUNT_SELF_EMPLOYMENT_TAX_PY',	'AMOUNT_SOCIAL_SEC_PY',	'AMOUNT_STATE_LOCAL_SALES_TAX_PY',	'AMOUNT_STATE_LOCAL_TAX_PY',	'AMOUNT_STUDENT_LOAN_INTEREST_DEDUCTION_PY',	'AMOUNT_TAX_CREDITS_PY',	'AMOUNT_TAX_DUE_PY',	'AMOUNT_TAX_PREP_FEES_PY',	'AMOUNT_TAX_PY',	'AMOUNT_TAXABLE_INCOME_PY',	'AMOUNT_TAXABLE_INTEREST_PY',	'AMOUNT_TAXABLE_IRA_PY',	'AMOUNT_TAXABLE_OFFSETS_PY',	'AMOUNT_TAXABLE_SOCIAL_SEC_PY',	'AMOUNT_TAXES_PAID_PY',	'AMOUNT_TOTAL_CREDITS_PY',	'AMOUNT_TOTAL_DEDUCTIBLE_EXPENSES_PY',	'AMOUNT_TOTAL_DEDUCTIONS_PY',	'AMOUNT_TOTAL_INCOME_PY',	'AMOUNT_TOTAL_INTEREST_PAID_PY',	'AMOUNT_TOTAL_PAYMENTS_PY',	'AMOUNT_TOTAL_TAX_PY',	'AMOUNT_TUITION_PY',	'AMOUNT_UNEMPLOYMENT_PY',	'AMOUNT_UNREPORTED_SS_MEDICARE_TAX_PY',	'BUS_COGS_INVENTORY_END_PY',	'BUS_COGS_INVENTORY_START_PY',	'BUS_COGS_LABOR_PY',	'BUS_COGS_PURCHASES_PY',	'BUS_COGS_PY',	'BUS_COGS_SUPPLIES_PY',	'BUS_COGS_TOTAL_PY',	'BUS_EXPENSE_ADVERTISING_PY',	'BUS_EXPENSE_CAR_PY',	'BUS_EXPENSE_COMMISSIONS_PY',	'BUS_EXPENSE_CONTRACT_LABOR_PY',	'BUS_EXPENSE_DEPLETION_PY',	'BUS_EXPENSE_DEPRECIATION_PY',	'BUS_EXPENSE_EMPLOYEE_BENEFITS_PY',	'BUS_EXPENSE_INSURANCE_PY',	'BUS_EXPENSE_LEGAL_PY',	'BUS_EXPENSE_MEALS_PY',	'BUS_EXPENSE_MORTGAGE_INTEREST_PY',	'BUS_EXPENSE_OFFICE_PY',	'BUS_EXPENSE_OTHER_INTEREST_PY',	'BUS_EXPENSE_OTHER_PY',	'BUS_EXPENSE_PENSION_PY',	'BUS_EXPENSE_PROFIT_TENTATIVE_PY',	'BUS_EXPENSE_RENT_OTHER_PY',	'BUS_EXPENSE_RENT_VEHICLES_PY',	'BUS_EXPENSE_REPAIRS_PY',	'BUS_EXPENSE_SUPPLIES_PY',	'BUS_EXPENSE_TAXES_PY',	'BUS_EXPENSE_TOTAL_PY',	'BUS_EXPENSE_TRAVEL_PY',	'BUS_EXPENSE_USE_OF_HOME_PY',	'BUS_EXPENSE_UTILITIES_PY',	'BUS_EXPENSE_WAGES_PY',	'BUS_GROSS_INCOME_PY',	'BUS_GROSS_PROFIT_PY',	'BUS_INVESTMENT_AT_RISK_PY',	'BUS_MATERIAL_PARTICIPATE_PY',	'BUS_NET_PROFIT_PY',	'BUS_OTHER_INCOME_PY',	'BUS_REQUIRE_1099_PY',	'BUS_START_ACQUIRE_PY',	'BUS_STATUTORY_EMPLOYEE_PY',	'BUS_VEHICLE_MILES_BUSINESS_PY',	'BUS_VEHICLE_MILES_COMMUTE_PY',	'BUS_VEHICLE_MILES_OTHER_PY',	'BUS_WILL_FILE_1099_PY',	'NUM_DEPENDENTS_PY',	'NUM_EXEMPTIONS_PY',	'SUP_EST_NONPASSIVE_INCOME_PY',	'SUP_EST_NONPASSIVE_LOSS_PY',	'SUP_EST_PASSIVE_INCOME_PY',	'SUP_EST_PASSIVE_LOSS_PY',	'SUP_EST_TOTAL_INCOME_PY',	'SUP_FARM_GROSS_INCOME_PY',	'SUP_FARM_RENTAL_INCOME_PY',	'SUP_PS_AT_RISK_PY',	'SUP_PS_NONPASSIVE_INCOME_PY',	'SUP_PS_NONPASSIVE_LOSS_PY',	'SUP_PS_PASSIVE_INCOME_PY',	'SUP_PS_PASSIVE_LOSS_PY',	'SUP_PS_PY_LOSS_PY',	'SUP_PS_SEC179_EXPENSE_DEDUCTION_PY',	'SUP_PS_TOTAL_INCOME_PY',	'SUP_RE_EXPENSES_ADVERTISING_PY',	'SUP_RE_EXPENSES_CLEANING_PY',	'SUP_RE_EXPENSES_COMMISSIONS_PY',	'SUP_RE_EXPENSES_DEDUCTIBLE_LOSS_PY',	'SUP_RE_EXPENSES_DEPRECIATION_PY',	'SUP_RE_EXPENSES_INSURANCE_PY',	'SUP_RE_EXPENSES_LEGAL_PY',	'SUP_RE_EXPENSES_MANAGEMENT_PY',	'SUP_RE_EXPENSES_MORTGAGE_INTEREST_PY',	'SUP_RE_EXPENSES_OTHER_INTEREST_PY',	'SUP_RE_EXPENSES_REPAIRS_PY',	'SUP_RE_EXPENSES_SUPPLIES_PY',	'SUP_RE_EXPENSES_TAXES_PY',	'SUP_RE_EXPENSES_TOTAL_PY',	'SUP_RE_EXPENSES_TRAVEL_PY',	'SUP_RE_EXPENSES_UTILITIES_PY',	'SUP_RE_INCOME_RENTS_PY',	'SUP_RE_INCOME_ROYALTIES_PY',	'SUP_RE_PERSONAL_DAYS_PY',	'SUP_RE_PROFESSIONAL_INCOME_PY',	'SUP_RE_TOTAL_INCOME_PY',	'SUP_REMIC_EXCESS_INCLUSION_PY',	'SUP_REMIC_SCHQ_INCOME_PY',	'SUP_REMIC_TAXABLE_INCOME_PY',	'BUS_ACCOUNTING_METHOD_ACCRUAL_PY',	'BUS_ACCOUNTING_METHOD_CASH_PY',	'BUS_ACCOUNTING_METHOD_OTHER_PY',	'BUS_COGS_METHOD_COST_OR_MARKET_PY',	'BUS_COGS_METHOD_COST_PY',	'BUS_COGS_METHOD_OTHER_PY',	'BUS_VEHICLE_PERSONAL_ANOTHER_PY',	'BUS_VEHICLE_PERSONAL_OFFDUTY_PY',	'SUP_PS_PARTNERSHIP_FOREIGN_PY',	'SUP_PS_PARTNERSHIP_PY',	'SUP_PS_SCORP_PY',	'SUP_RE_REQUIRE_1099_PY',	'SUP_RE_TYPE_COMMERCIAL_PY',	'SUP_RE_TYPE_LAND_PY',	'SUP_RE_TYPE_MULTI_FAMILY_PY',	'SUP_RE_TYPE_OTHER_PY',	'SUP_RE_TYPE_ROYALTIES_PY',	'SUP_RE_TYPE_SELF_RENTAL_PY',	'SUP_RE_TYPE_SHORT_RENTAL_PY',	'SUP_RE_TYPE_SINGLE_FAMILY_PY',	'SUP_RE_WILL_FILE_1099_PY']

        bool_features=['AUDIT_DEFENSE_FLAG_PY',	'CA_AUDIT_DEFENSE_FLAG_PY',	'CA_MAX_FLAG_PY',	'CA_REFUND_TRANSFER_FLAG_PY',	'CORE_FLAG_PY',	'FLAG_ITEMIZE_SEPARATELY_PY',	'FLAG_ITEMIZED_DEDUCTIONS_PY',	'FLAG_OLD_OR_BLIND_PY',	'FSCHA_FLAG_PY',	'FSCHC_FLAG_PY',	'FSCHCEZ_FLAG_PY',	'FSCHD_FLAG_PY',	'FSCHE_FLAG_PY',	'FSCHF_FLAG_PY',	'MAX_FLAG_PY',	'MINDBENDER_FLAG_PY',	'MISC1099_FLAG_PY',	'NON_CA_AUDIT_DEFENSE_FLAG_PY',	'NON_CA_MAX_FLAG_PY',	'NON_CA_REFUND_TRANSFER_FLAG_PY',	'PS_FLAG_PY',	'REFUND_TRANSFER_FLAG_PY',	'REQUIRED_TAKE_FLAG_PY',	'risk_flag_PY',	'RT_FLAG_PY',	'TTO_FLAG_PY',	'tto_start_flag_PY',	'vauth_flag_PY',	'_taxpayer_PY',	'accountant_spouse_PY',	'accountant_taxpayer_PY',	'accounting_spouse_PY',	'accountmanager_spouse_PY',	'accountmanager_taxpayer_PY',	'administrativeassistant_spouse_PY',	'administrativeassistant_taxpayer_PY',	'administrator_spouse_PY',	'analyst_spouse_PY',	'analyst_taxpayer_PY',	'assistantmanager_spouse_PY',	'assistantmanager_taxpayer_PY',	'attorney_spouse_PY',	'attorney_taxpayer_PY',	'banker_spouse_PY',	'banker_taxpayer_PY',	'bankteller_spouse_PY',	'bankteller_taxpayer_PY',	'barista_taxpayer_PY',	'bartender_spouse_PY',	'bartender_taxpayer_PY',	'bookkeeper_spouse_PY',	'caregiver_spouse_PY',	'caregiver_taxpayer_PY',	'carpenter_spouse_PY',	'carpenter_taxpayer_PY',	'cashier_spouse_PY',	'cashier_taxpayer_PY',	'chef_spouse_PY',	'chef_taxpayer_PY',	'clerical_spouse_PY',	'clerk_spouse_PY',	'clerk_taxpayer_PY',	'cna_spouse_PY',	'cna_taxpayer_PY',	'construction_spouse_PY',	'construction_taxpayer_PY',	'consultant_spouse_PY',	'consultant_taxpayer_PY',	'cook_spouse_PY',	'cook_taxpayer_PY',	'correctionalofficer_taxpayer_PY',	'crewmember_taxpayer_PY',	'csr_taxpayer_PY',	'custodian_spouse_PY',	'custodian_taxpayer_PY',	'customerservice_spouse_PY',	'customerservice_taxpayer_PY',	'customerservicerep_spouse_PY',	'customerservicerep_taxpayer_PY',	'deliverydriver_taxpayer_PY',	'dentalassistant_spouse_PY',	'dentalassistant_taxpayer_PY',	'director_spouse_PY',	'disable_spouse_PY',	'disabled_spouse_PY',	'disabled_taxpayer_PY',	'dispatcher_taxpayer_PY',	'driver_spouse_PY',	'driver_taxpayer_PY',	'educator_spouse_PY',	'electrician_spouse_PY',	'electrician_taxpayer_PY',	'employed_taxpayer_PY',	'employee_taxpayer_PY',	'engineer_spouse_PY',	'engineer_taxpayer_PY',	'executiveassistant_spouse_PY',	'factory_taxpayer_PY',	'factoryworker_spouse_PY',	'factoryworker_taxpayer_PY',	'fastfood_taxpayer_PY',	'foodservice_spouse_PY',	'foodservice_taxpayer_PY',	'generallabor_taxpayer_PY',	'generalmanager_taxpayer_PY',	'graphicdesigner_spouse_PY',	'hairstylist_spouse_PY',	'home_maker_spouse_PY',	'home_spouse_PY',	'homemaker_spouse_PY',	'homemaker_taxpayer_PY',	'hostess_taxpayer_PY',	'house_wife_spouse_PY',	'housekeeper_spouse_PY',	'housekeeper_taxpayer_PY',	'housekeeping_taxpayer_PY',	'housewife_spouse_PY',	'humanresources_spouse_PY',	'janitor_taxpayer_PY',	'labor_spouse_PY',	'labor_taxpayer_PY',	'laborer_spouse_PY',	'laborer_taxpayer_PY',	'lpn_spouse_PY',	'lpn_taxpayer_PY',	'machineoperator_spouse_PY',	'machineoperator_taxpayer_PY',	'machinist_spouse_PY',	'machinist_taxpayer_PY',	'maintenance_spouse_PY',	'maintenance_taxpayer_PY',	'management_taxpayer_PY',	'manager_spouse_PY',	'manager_taxpayer_PY',	'manufacturing_taxpayer_PY',	'marketing_spouse_PY',	'marketing_taxpayer_PY',	'mechanic_spouse_PY',	'mechanic_taxpayer_PY',	'medicalassistant_spouse_PY',	'medicalassistant_taxpayer_PY',	'military_spouse_PY',	'military_taxpayer_PY',	'mom_spouse_PY',	'mother_spouse_PY',	'na_spouse_PY',	'na_spouse2_PY',	'na_taxpayer_PY',	'none_spouse_PY',	'none_taxpayer_PY',	'nurse_spouse_PY',	'nurse_taxpayer_PY',	'officeassistant_spouse_PY',	'officemanager_spouse_PY',	'officemanager_taxpayer_PY',	'operationsmanager_taxpayer_PY',	'operator_taxpayer_PY',	'painter_taxpayer_PY',	'paralegal_spouse_PY',	'pharmacist_spouse_PY',	'pharmacytechnician_spouse_PY',	'pharmacytechnician_taxpayer_PY',	'physicaltherapist_spouse_PY',	'physician_spouse_PY',	'plumber_taxpayer_PY',	'policeofficer_spouse_PY',	'policeofficer_taxpayer_PY',	'production_taxpayer_PY',	'professor_spouse_PY',	'projectmanager_spouse_PY',	'projectmanager_taxpayer_PY',	'receptionist_spouse_PY',	'receptionist_taxpayer_PY',	'registerednurse_spouse_PY',	'registerednurse_taxpayer_PY',	'retail_spouse_PY',	'retail_taxpayer_PY',	'retailmanager_spouse_PY',	'retailmanager_taxpayer_PY',	'retired_spouse_PY',	'retired_taxpayer_PY',	'rn_spouse_PY',	'rn_taxpayer_PY',	'sales_spouse_PY',	'sales_taxpayer_PY',	'salesassociate_spouse_PY',	'salesassociate_taxpayer_PY',	'salesmanager_spouse_PY',	'salesmanager_taxpayer_PY',	'secretary_spouse_PY',	'secretary_taxpayer_PY',	'security_taxpayer_PY',	'securityguard_taxpayer_PY',	'securityofficer_taxpayer_PY',	'self_employed_spouse_PY',	'selfemployed_spouse_PY',	'selfemployed_taxpayer_PY',	'server_spouse_PY',	'server_taxpayer_PY',	'socialworker_spouse_PY',	'socialworker_taxpayer_PY',	'softwareengineer_spouse_PY',	'softwareengineer_taxpayer_PY',	'stayathomemom_spouse_PY',	'stayathomemother_spouse_PY',	'stayathomeparent_spouse_PY',	'stocker_taxpayer_PY',	'storemanager_taxpayer_PY',	'student_spouse_PY',	'student_taxpayer_PY',	'substituteteacher_spouse_PY',	'supervisor_spouse_PY',	'supervisor_taxpayer_PY',	'teacher_spouse_PY',	'teacher_taxpayer_PY',	'technician_spouse_PY',	'technician_taxpayer_PY',	'truckdriver_spouse_PY',	'truckdriver_taxpayer_PY',	'unemployed_spouse_PY',	'unemployed_taxpayer_PY',	'unemployeed_spouse_PY',	'waitress_spouse_PY',	'waitress_taxpayer_PY',	'warehouse_spouse_PY',	'warehouse_taxpayer_PY',	'warehouseworker_taxpayer_PY',	'welder_spouse_PY',	'welder_taxpayer_PY',	'worker_taxpayer_PY']

        catag_features=['auth_id_age_role_PY',	'LAST_FED_STATUS_PY',	'PRS_SCORE_PY',	'start_sku_rollup_id_PY',	'TAX_DAY_PY',	'TAX_WEEK_PY',	'auth_id_range_role_PY',	'channel_Group_PY',	'CHANNEL_PY',	'ENTRY_PAGE_GROUP_PY',	'SEASON_PART_PY',	'START_SKU_PY',	'neauth_app_type_PY',	'neauth_device_type_PY',	'neauth_platform_type_PY',	'start_app_type_PY',	'start_device_type_PY',	'start_platform_type_PY',	'vauth_app_type_PY',	'vauth_device_type_PY',	'vauth_platform_type_PY',	'START_SKU_ROLLUP_PY',	'FED_FORM_TYPE_PY',	'tto_segment_hybrid_PY',	'tto_segment_hybrid_rollup_PY',	'tto_segment_PY',	'tto_segment_rollup_PY',	'PRODUCT_EDITION_DESCRIPTION_PY',	'PRODUCT_ROLLUP_PY',	'CUSTOMER_TYPE_PY',	'EFILE_STATUS_DESCRIPTION_PY',	'CUSTOMER_DEFINITION_ADJ_PY',	'start_experience_PY',	'COMPLETED_SKU_PY',	'LAST_STATUS_PY',	'DMA_AREA_PY',	'FILING_STATUS_PY',	'ORDER_DATE_PY']

        cont_score_features = ['AUDIT_DEFENSE_FLAG_PY', 'CA_AUDIT_DEFENSE_FLAG_PY', 'CA_MAX_FLAG_PY',
        'CA_REFUND_TRANSFER_FLAG_PY', 'CORE_FLAG_PY', 'FLAG_ITEMIZE_SEPARATELY_PY',
        'FLAG_ITEMIZED_DEDUCTIONS_PY', 'FLAG_OLD_OR_BLIND_PY', 'FSCHA_FLAG_PY', 'FSCHC_FLAG_PY',
        'FSCHCEZ_FLAG_PY', 'FSCHD_FLAG_PY', 'FSCHE_FLAG_PY', 'FSCHF_FLAG_PY', 'MAX_FLAG_PY',
        'MINDBENDER_FLAG_PY', 'MISC1099_FLAG_PY', 'NON_CA_AUDIT_DEFENSE_FLAG_PY', 'NON_CA_MAX_FLAG_PY',
        'NON_CA_REFUND_TRANSFER_FLAG_PY', 'PS_FLAG_PY', 'REFUND_TRANSFER_FLAG_PY',
        'REQUIRED_TAKE_FLAG_PY', 'risk_flag_PY', 'RT_FLAG_PY', 'TTO_FLAG_PY', 'tto_start_flag_PY',
        'vauth_flag_PY', '_taxpayer_PY', 'accountant_spouse_PY', 'accountant_taxpayer_PY',
        'accounting_spouse_PY', 'accountmanager_spouse_PY', 'accountmanager_taxpayer_PY',
        'administrativeassistant_spouse_PY', 'administrativeassistant_taxpayer_PY',
        'administrator_spouse_PY', 'analyst_spouse_PY', 'analyst_taxpayer_PY',
        'assistantmanager_spouse_PY', 'assistantmanager_taxpayer_PY', 'attorney_spouse_PY',
        'attorney_taxpayer_PY', 'banker_spouse_PY', 'banker_taxpayer_PY', 'bankteller_spouse_PY',
        'bankteller_taxpayer_PY', 'barista_taxpayer_PY', 'bartender_spouse_PY',
        'bartender_taxpayer_PY', 'bookkeeper_spouse_PY', 'caregiver_spouse_PY',
        'caregiver_taxpayer_PY', 'carpenter_spouse_PY', 'carpenter_taxpayer_PY', 'cashier_spouse_PY',
        'cashier_taxpayer_PY', 'chef_spouse_PY', 'chef_taxpayer_PY', 'clerical_spouse_PY',
        'clerk_spouse_PY', 'clerk_taxpayer_PY', 'cna_spouse_PY', 'cna_taxpayer_PY',
        'construction_spouse_PY', 'construction_taxpayer_PY', 'consultant_spouse_PY',
        'consultant_taxpayer_PY', 'cook_spouse_PY', 'cook_taxpayer_PY',
        'correctionalofficer_taxpayer_PY', 'crewmember_taxpayer_PY', 'csr_taxpayer_PY',
        'custodian_spouse_PY', 'custodian_taxpayer_PY', 'customerservice_spouse_PY',
        'customerservice_taxpayer_PY', 'customerservicerep_spouse_PY',
        'customerservicerep_taxpayer_PY', 'deliverydriver_taxpayer_PY', 'dentalassistant_spouse_PY',
        'dentalassistant_taxpayer_PY', 'director_spouse_PY', 'disable_spouse_PY', 'disabled_spouse_PY',
        'disabled_taxpayer_PY', 'dispatcher_taxpayer_PY', 'driver_spouse_PY', 'driver_taxpayer_PY',
        'educator_spouse_PY', 'electrician_spouse_PY', 'electrician_taxpayer_PY',
        'employed_taxpayer_PY', 'employee_taxpayer_PY', 'engineer_spouse_PY', 'engineer_taxpayer_PY',
        'executiveassistant_spouse_PY', 'factory_taxpayer_PY', 'factoryworker_spouse_PY',
        'factoryworker_taxpayer_PY', 'fastfood_taxpayer_PY', 'foodservice_spouse_PY',
        'foodservice_taxpayer_PY', 'generallabor_taxpayer_PY', 'generalmanager_taxpayer_PY',
        'graphicdesigner_spouse_PY', 'hairstylist_spouse_PY', 'home_maker_spouse_PY', 'home_spouse_PY',
        'homemaker_spouse_PY', 'homemaker_taxpayer_PY', 'hostess_taxpayer_PY', 'house_wife_spouse_PY',
        'housekeeper_spouse_PY', 'housekeeper_taxpayer_PY', 'housekeeping_taxpayer_PY',
        'housewife_spouse_PY', 'humanresources_spouse_PY', 'janitor_taxpayer_PY', 'labor_spouse_PY',
        'labor_taxpayer_PY', 'laborer_spouse_PY', 'laborer_taxpayer_PY', 'lpn_spouse_PY',
        'lpn_taxpayer_PY', 'machineoperator_spouse_PY', 'machineoperator_taxpayer_PY',
        'machinist_spouse_PY', 'machinist_taxpayer_PY', 'maintenance_spouse_PY',
        'maintenance_taxpayer_PY', 'management_taxpayer_PY', 'manager_spouse_PY',
        'manager_taxpayer_PY', 'manufacturing_taxpayer_PY', 'marketing_spouse_PY',
        'marketing_taxpayer_PY', 'mechanic_spouse_PY', 'mechanic_taxpayer_PY',
        'medicalassistant_spouse_PY', 'medicalassistant_taxpayer_PY', 'military_spouse_PY',
        'military_taxpayer_PY', 'mom_spouse_PY', 'mother_spouse_PY', 'na_spouse_PY', 'na_spouse2_PY',
        'na_taxpayer_PY', 'none_spouse_PY', 'none_taxpayer_PY', 'nurse_spouse_PY', 'nurse_taxpayer_PY',
        'officeassistant_spouse_PY', 'officemanager_spouse_PY', 'officemanager_taxpayer_PY',
        'operationsmanager_taxpayer_PY', 'operator_taxpayer_PY', 'painter_taxpayer_PY',
        'paralegal_spouse_PY', 'pharmacist_spouse_PY', 'pharmacytechnician_spouse_PY',
        'pharmacytechnician_taxpayer_PY', 'physicaltherapist_spouse_PY', 'physician_spouse_PY',
        'plumber_taxpayer_PY', 'policeofficer_spouse_PY', 'policeofficer_taxpayer_PY',
        'production_taxpayer_PY', 'professor_spouse_PY', 'projectmanager_spouse_PY',
        'projectmanager_taxpayer_PY', 'receptionist_spouse_PY', 'receptionist_taxpayer_PY',
        'registerednurse_spouse_PY', 'registerednurse_taxpayer_PY', 'retail_spouse_PY',
        'retail_taxpayer_PY', 'retailmanager_spouse_PY', 'retailmanager_taxpayer_PY',
        'retired_spouse_PY', 'retired_taxpayer_PY', 'rn_spouse_PY', 'rn_taxpayer_PY',
        'sales_spouse_PY', 'sales_taxpayer_PY', 'salesassociate_spouse_PY',
        'salesassociate_taxpayer_PY', 'salesmanager_spouse_PY', 'salesmanager_taxpayer_PY',
        'secretary_spouse_PY', 'secretary_taxpayer_PY', 'security_taxpayer_PY',
        'securityguard_taxpayer_PY', 'securityofficer_taxpayer_PY', 'self_employed_spouse_PY',
        'selfemployed_spouse_PY', 'selfemployed_taxpayer_PY', 'server_spouse_PY', 'server_taxpayer_PY',
        'socialworker_spouse_PY', 'socialworker_taxpayer_PY', 'softwareengineer_spouse_PY',
        'softwareengineer_taxpayer_PY', 'stayathomemom_spouse_PY', 'stayathomemother_spouse_PY',
        'stayathomeparent_spouse_PY', 'stocker_taxpayer_PY', 'storemanager_taxpayer_PY',
        'student_spouse_PY', 'student_taxpayer_PY', 'substituteteacher_spouse_PY',
        'supervisor_spouse_PY', 'supervisor_taxpayer_PY', 'teacher_spouse_PY', 'teacher_taxpayer_PY',
        'technician_spouse_PY', 'technician_taxpayer_PY', 'truckdriver_spouse_PY',
        'truckdriver_taxpayer_PY', 'unemployed_spouse_PY', 'unemployed_taxpayer_PY',
        'unemployeed_spouse_PY', 'waitress_spouse_PY', 'waitress_taxpayer_PY', 'warehouse_spouse_PY',
        'warehouse_taxpayer_PY', 'warehouseworker_taxpayer_PY', 'welder_spouse_PY',
        'welder_taxpayer_PY', 'worker_taxpayer_PY', 'NUM_CARE_CONTACTS_PY', 'NUM_SCHC_PY',
        'NUM_SCHE_PY', 'NUM_W2_PY', 'REJECT_COUNT_PY', 'STATE_ATTACH_COUNT_PY', 'FEDERAL_REVENUE_PY',
        'TOTAL_REVENUE_PY', 'AGI_PY', 'AMOUNT_ADJUSTMENTS_PY', 'AMOUNT_ALIMONY_INCOME_PY',
        'AMOUNT_ALIMONY_PAID_PY', 'AMOUNT_AMT_PY', 'AMOUNT_BUSINESS_INCOME_PY',
        'AMOUNT_CAPITAL_GAIN_PY', 'AMOUNT_CASUALTY_LOSSES_PY', 'AMOUNT_CERTAIN_BUSINESS_EXPENSE_PY',
        'AMOUNT_CHARITABLE_CONTRIBUTIONS_CARRYOVER_PY', 'AMOUNT_CHARITABLE_CONTRIBUTIONS_CASH_PY',
        'AMOUNT_CHARITABLE_CONTRIBUTIONS_NONCASH_PY', 'AMOUNT_CHARITABLE_CONTRIBUTIONS_PY',
        'AMOUNT_CHILD_CARE_CREDIT_PY', 'AMOUNT_CHILD_CREDIT_PY',
        'AMOUNT_DEDUCTIBLE_SELF_EMPLOYMENT_TAX_PY', 'AMOUNT_DISABLED_CREDIT_PY',
        'AMOUNT_DOMESTIC_PRODUCTION_DEDUCTION_PY', 'AMOUNT_EARLY_WITHDRAWAL_PENALTY_PY',
        'AMOUNT_EDUCATION_CREDIT_PY', 'AMOUNT_EITC_PY', 'AMOUNT_EMPLOYEE_EXPENSES_PY',
        'AMOUNT_ESTIMATED_TAX_PENALTY_PY', 'AMOUNT_ESTIMATED_TAX_PY',
        'AMOUNT_EXCESS_SS_RRTA_WITHHELD_PY', 'AMOUNT_EXEMPTIONS_PY', 'AMOUNT_EXPENSES_DEDUCTION_PY',
        'AMOUNT_FARM_INCOME_PY', 'AMOUNT_FOREIGN_TAX_CREDIT_PY', 'AMOUNT_FUEL_TAX_CREDIT_PY',
        'AMOUNT_HOMEBUYER_CREDIT_REPAYMENT_PY', 'AMOUNT_HOPE_CREDIT_PY', 'AMOUNT_HSA_PY',
        'AMOUNT_INCOME_TAX_PY', 'AMOUNT_INCOME_TAX_WITHHELD_PY', 'AMOUNT_INVESTMENT_INTEREST_PAID_PY',
        'AMOUNT_IRA_DEDUCTION_PY', 'AMOUNT_IRA_DISTRIBUTIONS_PY',
        'AMOUNT_MEDICAL_DENTAL_EXPENSES_DEDUCTION_PY', 'AMOUNT_MEDICAL_DENTAL_EXPENSES_PY',
        'AMOUNT_MISC_DEDUCTIONS_PY', 'AMOUNT_MORTGAGE_INSURANCE_PY',
        'AMOUNT_MORTGAGE_INTEREST_NON_1098_PY', 'AMOUNT_MORTGAGE_INTEREST_PY',
        'AMOUNT_MORTGAGE_POINTS_NON_1098_PY', 'AMOUNT_MOVING_EXPENSE_PY', 'AMOUNT_NT_COMBAT_PAY_PY',
        'AMOUNT_ORDINARY_DIVIDENDS_PY', 'AMOUNT_OTHER_CREDITS_PY',
        'AMOUNT_OTHER_DEDUCTIBLE_EXPENSES_PY', 'AMOUNT_OTHER_DEDUCTIBLE_TAXES_PY',
        'AMOUNT_OTHER_GAIN_PY', 'AMOUNT_OTHER_INCOME_PY', 'AMOUNT_OTHER_PAYMENTS_PY',
        'AMOUNT_OTHER_TAXES_PY', 'AMOUNT_PAID_WITH_EXTENSION_PY', 'AMOUNT_PERSONAL_PROPERTY_TAXES_PY',
        'AMOUNT_QUALIFIED_DIVIDENDS_PY', 'AMOUNT_REAL_ESTATE_TAX_PY', 'AMOUNT_REFUND_PY',
        'AMOUNT_RESIDENTIAL_ENERGY_CREDIT_PY', 'AMOUNT_RETIREMENT_SAVINGS_CREDIT_PY',
        'AMOUNT_SALARIES_AND_WAGES_PY', 'AMOUNT_SCHE_PY', 'AMOUNT_SELF_EMPLOYMENT_HEALTH_INSURANCE_PY',
        'AMOUNT_SELF_EMPLOYMENT_RETIREMENT_PY', 'AMOUNT_SELF_EMPLOYMENT_TAX_PY',
        'AMOUNT_SOCIAL_SEC_PY', 'AMOUNT_STATE_LOCAL_SALES_TAX_PY', 'AMOUNT_STATE_LOCAL_TAX_PY',
        'AMOUNT_STUDENT_LOAN_INTEREST_DEDUCTION_PY', 'AMOUNT_TAX_CREDITS_PY', 'AMOUNT_TAX_DUE_PY',
        'AMOUNT_TAX_PREP_FEES_PY', 'AMOUNT_TAX_PY', 'AMOUNT_TAXABLE_INCOME_PY',
        'AMOUNT_TAXABLE_INTEREST_PY', 'AMOUNT_TAXABLE_IRA_PY', 'AMOUNT_TAXABLE_OFFSETS_PY',
        'AMOUNT_TAXABLE_SOCIAL_SEC_PY', 'AMOUNT_TAXES_PAID_PY', 'AMOUNT_TOTAL_CREDITS_PY',
        'AMOUNT_TOTAL_DEDUCTIBLE_EXPENSES_PY', 'AMOUNT_TOTAL_DEDUCTIONS_PY', 'AMOUNT_TOTAL_INCOME_PY',
        'AMOUNT_TOTAL_INTEREST_PAID_PY', 'AMOUNT_TOTAL_PAYMENTS_PY', 'AMOUNT_TOTAL_TAX_PY',
        'AMOUNT_TUITION_PY', 'AMOUNT_UNEMPLOYMENT_PY', 'AMOUNT_UNREPORTED_SS_MEDICARE_TAX_PY',
        'BUS_COGS_INVENTORY_END_PY', 'BUS_COGS_INVENTORY_START_PY', 'BUS_COGS_LABOR_PY',
        'BUS_COGS_PURCHASES_PY', 'BUS_COGS_PY', 'BUS_COGS_SUPPLIES_PY', 'BUS_COGS_TOTAL_PY',
        'BUS_EXPENSE_ADVERTISING_PY', 'BUS_EXPENSE_CAR_PY', 'BUS_EXPENSE_COMMISSIONS_PY',
        'BUS_EXPENSE_CONTRACT_LABOR_PY', 'BUS_EXPENSE_DEPLETION_PY', 'BUS_EXPENSE_DEPRECIATION_PY',
        'BUS_EXPENSE_EMPLOYEE_BENEFITS_PY', 'BUS_EXPENSE_INSURANCE_PY', 'BUS_EXPENSE_LEGAL_PY',
        'BUS_EXPENSE_MEALS_PY', 'BUS_EXPENSE_MORTGAGE_INTEREST_PY', 'BUS_EXPENSE_OFFICE_PY',
        'BUS_EXPENSE_OTHER_INTEREST_PY', 'BUS_EXPENSE_OTHER_PY', 'BUS_EXPENSE_PENSION_PY',
        'BUS_EXPENSE_PROFIT_TENTATIVE_PY', 'BUS_EXPENSE_RENT_OTHER_PY', 'BUS_EXPENSE_RENT_VEHICLES_PY',
        'BUS_EXPENSE_REPAIRS_PY', 'BUS_EXPENSE_SUPPLIES_PY', 'BUS_EXPENSE_TAXES_PY',
        'BUS_EXPENSE_TOTAL_PY', 'BUS_EXPENSE_TRAVEL_PY', 'BUS_EXPENSE_USE_OF_HOME_PY',
        'BUS_EXPENSE_UTILITIES_PY', 'BUS_EXPENSE_WAGES_PY', 'BUS_GROSS_INCOME_PY',
        'BUS_GROSS_PROFIT_PY', 'BUS_INVESTMENT_AT_RISK_PY', 'BUS_MATERIAL_PARTICIPATE_PY',
        'BUS_NET_PROFIT_PY', 'BUS_OTHER_INCOME_PY', 'BUS_REQUIRE_1099_PY', 'BUS_START_ACQUIRE_PY',
        'BUS_STATUTORY_EMPLOYEE_PY', 'BUS_VEHICLE_MILES_BUSINESS_PY', 'BUS_VEHICLE_MILES_COMMUTE_PY',
        'BUS_VEHICLE_MILES_OTHER_PY', 'BUS_WILL_FILE_1099_PY', 'NUM_DEPENDENTS_PY',
        'NUM_EXEMPTIONS_PY', 'SUP_EST_NONPASSIVE_INCOME_PY', 'SUP_EST_NONPASSIVE_LOSS_PY',
        'SUP_EST_PASSIVE_INCOME_PY', 'SUP_EST_PASSIVE_LOSS_PY', 'SUP_EST_TOTAL_INCOME_PY',
        'SUP_FARM_GROSS_INCOME_PY', 'SUP_FARM_RENTAL_INCOME_PY', 'SUP_PS_AT_RISK_PY',
        'SUP_PS_NONPASSIVE_INCOME_PY', 'SUP_PS_NONPASSIVE_LOSS_PY', 'SUP_PS_PASSIVE_INCOME_PY',
        'SUP_PS_PASSIVE_LOSS_PY', 'SUP_PS_PY_LOSS_PY', 'SUP_PS_SEC179_EXPENSE_DEDUCTION_PY',
        'SUP_PS_TOTAL_INCOME_PY', 'SUP_RE_EXPENSES_ADVERTISING_PY', 'SUP_RE_EXPENSES_CLEANING_PY',
        'SUP_RE_EXPENSES_COMMISSIONS_PY', 'SUP_RE_EXPENSES_DEDUCTIBLE_LOSS_PY',
        'SUP_RE_EXPENSES_DEPRECIATION_PY', 'SUP_RE_EXPENSES_INSURANCE_PY', 'SUP_RE_EXPENSES_LEGAL_PY',
        'SUP_RE_EXPENSES_MANAGEMENT_PY', 'SUP_RE_EXPENSES_MORTGAGE_INTEREST_PY',
        'SUP_RE_EXPENSES_OTHER_INTEREST_PY', 'SUP_RE_EXPENSES_REPAIRS_PY',
        'SUP_RE_EXPENSES_SUPPLIES_PY', 'SUP_RE_EXPENSES_TAXES_PY', 'SUP_RE_EXPENSES_TOTAL_PY',
        'SUP_RE_EXPENSES_TRAVEL_PY', 'SUP_RE_EXPENSES_UTILITIES_PY', 'SUP_RE_INCOME_RENTS_PY',
        'SUP_RE_INCOME_ROYALTIES_PY', 'SUP_RE_PERSONAL_DAYS_PY', 'SUP_RE_PROFESSIONAL_INCOME_PY',
        'SUP_RE_TOTAL_INCOME_PY', 'SUP_REMIC_EXCESS_INCLUSION_PY', 'SUP_REMIC_SCHQ_INCOME_PY',
        'SUP_REMIC_TAXABLE_INCOME_PY', 'BUS_ACCOUNTING_METHOD_ACCRUAL_PY',
        'BUS_ACCOUNTING_METHOD_CASH_PY', 'BUS_ACCOUNTING_METHOD_OTHER_PY',
        'BUS_COGS_METHOD_COST_OR_MARKET_PY', 'BUS_COGS_METHOD_COST_PY', 'BUS_COGS_METHOD_OTHER_PY',
        'BUS_VEHICLE_PERSONAL_ANOTHER_PY', 'BUS_VEHICLE_PERSONAL_OFFDUTY_PY',
        'SUP_PS_PARTNERSHIP_FOREIGN_PY', 'SUP_PS_PARTNERSHIP_PY', 'SUP_PS_SCORP_PY',
        'SUP_RE_REQUIRE_1099_PY', 'SUP_RE_TYPE_COMMERCIAL_PY', 'SUP_RE_TYPE_LAND_PY',
        'SUP_RE_TYPE_MULTI_FAMILY_PY', 'SUP_RE_TYPE_OTHER_PY', 'SUP_RE_TYPE_ROYALTIES_PY',
        'SUP_RE_TYPE_SELF_RENTAL_PY', 'SUP_RE_TYPE_SHORT_RENTAL_PY', 'SUP_RE_TYPE_SINGLE_FAMILY_PY',
        'SUP_RE_WILL_FILE_1099_PY']

        bool_score_features = ['AUDIT_DEFENSE_FLAG_PY', 'CA_AUDIT_DEFENSE_FLAG_PY', 'CA_MAX_FLAG_PY',
        'CA_REFUND_TRANSFER_FLAG_PY', 'CORE_FLAG_PY', 'FLAG_ITEMIZE_SEPARATELY_PY',
        'FLAG_ITEMIZED_DEDUCTIONS_PY', 'FLAG_OLD_OR_BLIND_PY', 'FSCHA_FLAG_PY', 'FSCHC_FLAG_PY',
        'FSCHCEZ_FLAG_PY', 'FSCHD_FLAG_PY', 'FSCHE_FLAG_PY', 'FSCHF_FLAG_PY', 'MAX_FLAG_PY',
        'MINDBENDER_FLAG_PY', 'MISC1099_FLAG_PY', 'NON_CA_AUDIT_DEFENSE_FLAG_PY', 'NON_CA_MAX_FLAG_PY',
        'NON_CA_REFUND_TRANSFER_FLAG_PY', 'PS_FLAG_PY', 'REFUND_TRANSFER_FLAG_PY',
        'REQUIRED_TAKE_FLAG_PY', 'risk_flag_PY', 'RT_FLAG_PY', 'TTO_FLAG_PY', 'tto_start_flag_PY',
        'vauth_flag_PY', '_taxpayer_PY', 'accountant_spouse_PY', 'accountant_taxpayer_PY',
        'accounting_spouse_PY', 'accountmanager_spouse_PY', 'accountmanager_taxpayer_PY',
        'administrativeassistant_spouse_PY', 'administrativeassistant_taxpayer_PY',
        'administrator_spouse_PY', 'analyst_spouse_PY', 'analyst_taxpayer_PY',
        'assistantmanager_spouse_PY', 'assistantmanager_taxpayer_PY', 'attorney_spouse_PY',
        'attorney_taxpayer_PY', 'banker_spouse_PY', 'banker_taxpayer_PY', 'bankteller_spouse_PY',
        'bankteller_taxpayer_PY', 'barista_taxpayer_PY', 'bartender_spouse_PY',
        'bartender_taxpayer_PY', 'bookkeeper_spouse_PY', 'caregiver_spouse_PY',
        'caregiver_taxpayer_PY', 'carpenter_spouse_PY', 'carpenter_taxpayer_PY', 'cashier_spouse_PY',
        'cashier_taxpayer_PY', 'chef_spouse_PY', 'chef_taxpayer_PY', 'clerical_spouse_PY',
        'clerk_spouse_PY', 'clerk_taxpayer_PY', 'cna_spouse_PY', 'cna_taxpayer_PY',
        'construction_spouse_PY', 'construction_taxpayer_PY', 'consultant_spouse_PY',
        'consultant_taxpayer_PY', 'cook_spouse_PY', 'cook_taxpayer_PY',
        'correctionalofficer_taxpayer_PY', 'crewmember_taxpayer_PY', 'csr_taxpayer_PY',
        'custodian_spouse_PY', 'custodian_taxpayer_PY', 'customerservice_spouse_PY',
        'customerservice_taxpayer_PY', 'customerservicerep_spouse_PY',
        'customerservicerep_taxpayer_PY', 'deliverydriver_taxpayer_PY', 'dentalassistant_spouse_PY',
        'dentalassistant_taxpayer_PY', 'director_spouse_PY', 'disable_spouse_PY', 'disabled_spouse_PY',
        'disabled_taxpayer_PY', 'dispatcher_taxpayer_PY', 'driver_spouse_PY', 'driver_taxpayer_PY',
        'educator_spouse_PY', 'electrician_spouse_PY', 'electrician_taxpayer_PY',
        'employed_taxpayer_PY', 'employee_taxpayer_PY', 'engineer_spouse_PY', 'engineer_taxpayer_PY',
        'executiveassistant_spouse_PY', 'factory_taxpayer_PY', 'factoryworker_spouse_PY',
        'factoryworker_taxpayer_PY', 'fastfood_taxpayer_PY', 'foodservice_spouse_PY',
        'foodservice_taxpayer_PY', 'generallabor_taxpayer_PY', 'generalmanager_taxpayer_PY',
        'graphicdesigner_spouse_PY', 'hairstylist_spouse_PY', 'home_maker_spouse_PY', 'home_spouse_PY',
        'homemaker_spouse_PY', 'homemaker_taxpayer_PY', 'hostess_taxpayer_PY', 'house_wife_spouse_PY',
        'housekeeper_spouse_PY', 'housekeeper_taxpayer_PY', 'housekeeping_taxpayer_PY',
        'housewife_spouse_PY', 'humanresources_spouse_PY', 'janitor_taxpayer_PY', 'labor_spouse_PY',
        'labor_taxpayer_PY', 'laborer_spouse_PY', 'laborer_taxpayer_PY', 'lpn_spouse_PY',
        'lpn_taxpayer_PY', 'machineoperator_spouse_PY', 'machineoperator_taxpayer_PY',
        'machinist_spouse_PY', 'machinist_taxpayer_PY', 'maintenance_spouse_PY',
        'maintenance_taxpayer_PY', 'management_taxpayer_PY', 'manager_spouse_PY',
        'manager_taxpayer_PY', 'manufacturing_taxpayer_PY', 'marketing_spouse_PY',
        'marketing_taxpayer_PY', 'mechanic_spouse_PY', 'mechanic_taxpayer_PY',
        'medicalassistant_spouse_PY', 'medicalassistant_taxpayer_PY', 'military_spouse_PY',
        'military_taxpayer_PY', 'mom_spouse_PY', 'mother_spouse_PY', 'na_spouse_PY', 'na_spouse2_PY',
        'na_taxpayer_PY', 'none_spouse_PY', 'none_taxpayer_PY', 'nurse_spouse_PY', 'nurse_taxpayer_PY',
        'officeassistant_spouse_PY', 'officemanager_spouse_PY', 'officemanager_taxpayer_PY',
        'operationsmanager_taxpayer_PY', 'operator_taxpayer_PY', 'painter_taxpayer_PY',
        'paralegal_spouse_PY', 'pharmacist_spouse_PY', 'pharmacytechnician_spouse_PY',
        'pharmacytechnician_taxpayer_PY', 'physicaltherapist_spouse_PY', 'physician_spouse_PY',
        'plumber_taxpayer_PY', 'policeofficer_spouse_PY', 'policeofficer_taxpayer_PY',
        'production_taxpayer_PY', 'professor_spouse_PY', 'projectmanager_spouse_PY',
        'projectmanager_taxpayer_PY', 'receptionist_spouse_PY', 'receptionist_taxpayer_PY',
        'registerednurse_spouse_PY', 'registerednurse_taxpayer_PY', 'retail_spouse_PY',
        'retail_taxpayer_PY', 'retailmanager_spouse_PY', 'retailmanager_taxpayer_PY',
        'retired_spouse_PY', 'retired_taxpayer_PY', 'rn_spouse_PY', 'rn_taxpayer_PY',
        'sales_spouse_PY', 'sales_taxpayer_PY', 'salesassociate_spouse_PY',
        'salesassociate_taxpayer_PY', 'salesmanager_spouse_PY', 'salesmanager_taxpayer_PY',
        'secretary_spouse_PY', 'secretary_taxpayer_PY', 'security_taxpayer_PY',
        'securityguard_taxpayer_PY', 'securityofficer_taxpayer_PY', 'self_employed_spouse_PY',
        'selfemployed_spouse_PY', 'selfemployed_taxpayer_PY', 'server_spouse_PY', 'server_taxpayer_PY',
        'socialworker_spouse_PY', 'socialworker_taxpayer_PY', 'softwareengineer_spouse_PY',
        'softwareengineer_taxpayer_PY', 'stayathomemom_spouse_PY', 'stayathomemother_spouse_PY',
        'stayathomeparent_spouse_PY', 'stocker_taxpayer_PY', 'storemanager_taxpayer_PY',
        'student_spouse_PY', 'student_taxpayer_PY', 'substituteteacher_spouse_PY',
        'supervisor_spouse_PY', 'supervisor_taxpayer_PY', 'teacher_spouse_PY', 'teacher_taxpayer_PY',
        'technician_spouse_PY', 'technician_taxpayer_PY', 'truckdriver_spouse_PY',
        'truckdriver_taxpayer_PY', 'unemployed_spouse_PY', 'unemployed_taxpayer_PY',
        'unemployeed_spouse_PY', 'waitress_spouse_PY', 'waitress_taxpayer_PY', 'warehouse_spouse_PY',
        'warehouse_taxpayer_PY', 'warehouseworker_taxpayer_PY', 'welder_spouse_PY',
        'welder_taxpayer_PY', 'worker_taxpayer_PY']

        catag_score_features = ['auth_id_age_role_PY', 'LAST_FED_STATUS_PY', 'PRS_SCORE_PY', 'start_sku_rollup_id_PY',
        'TAX_DAY_PY', 'TAX_WEEK_PY', 'auth_id_range_role_PY', 'channel_Group_PY', 'CHANNEL_PY',
        'ENTRY_PAGE_GROUP_PY', 'SEASON_PART_PY', 'START_SKU_PY', 'neauth_app_type_PY',
        'neauth_device_type_PY', 'neauth_platform_type_PY', 'start_app_type_PY',
        'start_device_type_PY', 'start_platform_type_PY', 'vauth_app_type_PY', 'vauth_device_type_PY',
        'vauth_platform_type_PY', 'START_SKU_ROLLUP_PY', 'FED_FORM_TYPE_PY', 'tto_segment_hybrid_PY',
        'tto_segment_hybrid_rollup_PY', 'tto_segment_PY', 'tto_segment_rollup_PY',
        'PRODUCT_EDITION_DESCRIPTION_PY', 'PRODUCT_ROLLUP_PY', 'CUSTOMER_TYPE_PY',
        'EFILE_STATUS_DESCRIPTION_PY', 'CUSTOMER_DEFINITION_ADJ_PY', 'start_experience_PY',
        'COMPLETED_SKU_PY', 'LAST_STATUS_PY', 'DMA_AREA_PY', 'FILING_STATUS_PY', 'ORDER_DATE_PY']
    return cont_features, bool_features, catag_features, cont_score_features, bool_score_features, catag_score_features